logging:
  level:
    root: INFO
    com.wex.payments: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{traceId:-no-trace}] [%X{purchaseId:-no-purchase}] %logger{36} - %msg%n"

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

treasury:
  api:
    base-url: https://api.fiscaldata.treasury.gov
    rates-of-exchange-path: /services/api/fiscal_service/v1/accounting/od/rates_of_exchange
    connect-timeout: 2s
    read-timeout: 5s
    max-attempts: 3

server:
  error:
    include-message: never

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
      show-components: always
      group:
        readiness:
          include: readinessState,db,treasuryApi
