logging:
  level:
    root: INFO
    com.wex.payments: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{traceId:-no-trace}] [%X{purchaseId:-no-purchase}] %logger{36} - %msg%n"

spring:
  datasource:
    url: jdbc:h2:mem:corporatepayments;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

treasury:
  api:
    base-url: https://api.fiscaldata.treasury.gov
    rates-of-exchange-path: /services/api/fiscal_service/v1/accounting/od/rates_of_exchange

server:
  error:
    include-message: never
