logging:
  level:
    root: INFO
    com.wex.payments: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/corporate_payments
    username: corporate_payments
    password: corporate_payments

treasury:
  api:
    base-url: https://api.fiscaldata.treasury.gov
    connect-timeout: 2s
    read-timeout: 5s
    max-attempts: 3
